version: '3.8'

services:
  russian-phone-bot:
    build: .
    container_name: russian_phone_bot
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - TZ=Europe/Moscow
    restart: unless-stopped
    volumes:
      - bot_logs:/tmp
    networks:
      - bot_network
    logging:
      driver: "json-file"  
      options:
        max-size: "10m"
        max-file: "5"
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('https://api.telegram.org/bot${BOT_TOKEN}/getMe').raise_for_status()"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  bot_logs:

networks:
  bot_network:
    driver: bridge